apiVersion: batch/v1
kind: Job
metadata:
  name: client
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
        - name: client
          image: client:testclient
      restartPolicy: Never
